name: create document

on:
  push:
      
jobs:
  change:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
          
      - name: install lib
        run: |
          cd docs
          pip install -r requirements.txt
          
      - name: change
        run: |
          sphinx-apidoc -f -o ./ ./_build
          make html

      - name: Commit and Push
        run: |
          cd ./_build
          git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git config --global user.name "tuna2134"
          git config --global user.email "masato190411@gmail.com"
          git add .
          git commit -m "add document"
          git checkout -b gh-pages
          git push origin gh-pages
