name: create document

on:
  release:
    types: [created]
      
jobs:
  change:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          
      - name: install lib
        run: |
          pip install sphinx sphinx_rtd_theme
          
      - name: change
        run: |
          sphinx-apidoc -f -o /docs/google_custom_search ./google-custom-search
          cd docs
          make html

      - name: Commit and Push
        run: |
          git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git config --global user.name "tuna2134"
          git config --global user.email "masato190411@gmail.com"
          git add .
          git commit -m "add document"
          git checkout -b master
          git push origin master
